# Generated by Django 4.0.2 on 2022-03-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auctionlisting_starting_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='highestbid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid',
            field=models.FloatField(),
        ),
    ]
