# Generated by Django 4.0.2 on 2022-03-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bid_highestbid_alter_bid_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='winningbid',
            field=models.BooleanField(default=False),
        ),
    ]
